### ISSUE TITLE
sharing idea one

### ISSUE THREAD

**Issue by Ansper11** [yyht6300a/499Project-Minecraft-C#2]

**Comment by caincdiy** [comment]
AI and ML are based on computer science and programming, but the student in middle school may not know what python is, and in elementary school, there are a lot of students using Block-base programming language like Scratch. Therefore, how to help middle school students to switch from Scratch to Python can be a good point in our project.

**Comment by caincdiy** [comment]
AI and ML are based on computer science and programming, but the student in middle school may not know what python is, and in elementary school, there are a lot of students using Block-base programming language like Scratch. Therefore, how to help middle school students to switch from Scratch to Python can be a good point in our project.

**Comment by Ansper11** [comment]
sharing idea
